server:
  port: 8080

spring:
  jackson:
    time-zone: UTC
  application:
    name: "back-auth-service"

    datasource:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:name_db}
      username: ${USER_DB:user}
      password: ${PASS_DB:user}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        autoCommit: true
        connectionTimeout: 30000
        idleTimeout: 600000
        keepaliveTime: 120000
        maxLifetime: 1800000
        maximumPoolSize: 50
        minimumIdle: 8
        poolName: PoolConnection-ArkaProyect-Auth
        leakDetectionThreshold: 30000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always
jwt-provider:
  expiration-date : 3600000
  secret: "sM|<EjC=de:|TC/(/ldr)ELFeqV$}dDwqn}/mZ5A2ug"
  password-rest:
    token-expiration-minutes: 30
cloud-provider:
  aws:
    s3:
      bucket-name:
        objects:
          templateHtml:
    ses:
      sender: